CREATE SEQUENCE IF NOT EXISTS hibernate_sequence;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  id_provider VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  avatar_url VARCHAR(250) NOT NULL
);

